### ISSUE TITLE
Server-side rendering throws error

### ISSUE THREAD

**Issue by dllabs** [swimlane/ngx-datatable#1157]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

When built and run with server-side rendering (`npm run build:ssr && npm run serve:ssr`) the ngx-datatable module throws this critical (showstopping) error:

    ERROR TypeError: this.element.getBoundingClientRect is not a function
    at DatatableComponent.recalculateDims (C:\Users\jtdav\Documents\Projects\universal-starter-master\dist\server.js:101998:33)
    at DatatableComponent.recalculate (C:\Users\jtdav\Documents\Projects\universal-starter-master\dist\server.js:101961:14)
    at DatatableComponent.set [as rows] (C:\Users\jtdav\Documents\Projects\universal-starter-master\dist\server.js:101606:18)
    at updateProp (C:\Users\jtdav\Documents\Projects\universal-starter-master\dist\server.js:12884:37)
    at checkAndUpdateDirectiveInline (C:\Users\jtdav\Documents\Projects\universal-starter-master\dist\server.js:12593:19)
    at checkAndUpdateNodeInline (C:\Users\jtdav\Documents\Projects\universal-starter-master\dist\server.js:14138:20)
    at checkAndUpdateNode (C:\Users\jtdav\Documents\Projects\universal-starter-master\dist\server.js:14081:16)
    at prodCheckAndUpdateNode (C:\Users\jtdav\Documents\Projects\universal-starter-master\dist\server.js:14784:5)
    at Object.updateDirectives (C:\Users\jtdav\Documents\Projects\universal-starter-master\dist\server.js:110774:6478)
    at Object.updateDirectives (C:\Users\jtdav\Documents\Projects\universal-starter-master\dist\server.js:14525:29)

As per @earlyster's [previous discussions about server-side rendering](https://github.com/swimlane/ngx-datatable/issues/173), it has to do with the server-side renderer trying to get the dimensions of the viewport.

**Expected behavior**

It should run without errors. Where it gets the viewport dimensions from is unclear to me. If there is already a way to pass the viewport dimensions to the server, then perhaps the documentation could be updated to show how?

**Reproduction of the problem**

1) Clone [Angular Universal Starter](https://github.com/angular/universal-starter) and install dependencies.
2) Install ngx-datatable and configure with dummy data as per the [current documentation](https://swimlane.gitbooks.io/ngx-datatable/introduction/getting-started.html).
3) Run client-side with `ng serve`. It runs without errors.
4) Build and run server-side with `npm run build:ssr && npm run serve:ssr`. It throws the above error.

**Please tell us about your environment:**

* **Table version:** 11.1.4

* **Angular version:** 5.0.3

* **Browser:** Error happens in node express server itself

* **Language:** Typescript 2.6.1

**Comment by krumelist** [comment]
I have a similiar problem with .NET Core Angular application:
`Microsoft.AspNetCore.NodeServices:Error: ERROR TypeError: this.document.createElement is not a function
    at ScrollbarHelper../src/services/scrollbar-helper.service.ts.ScrollbarHelper.getWidth (c:\...\ClientApp\dist\main-server.js:36597:35)
    at new ScrollbarHelper (c:\...\ClientApp\dist\main-server.js:36594:27)
    at _createClass (c:\...\ClientApp\dist\vendor.js:20469:26)
    at _createProviderInstance$1 (c:\...\ClientApp\dist\vendor.js:20441:26)
    at resolveNgModuleDep (c:\...\ClientApp\dist\vendor.js:20426:17)
    at NgModuleRef_.module.exports.NgModuleRef_.get (c:\...\ClientApp\dist\vendor.js:21512:16)
    at resolveDep (c:\...\ClientApp\dist\vendor.js:22015:45)
    at createClass (c:\...\ClientApp\dist\vendor.js:21879:32)
    at createDirectiveInstance (c:\...\ClientApp\dist\vendor.js:21699:37)
    at createViewNodes (c:\...\ClientApp\dist\vendor.js:23127:49)`
