### ISSUE TITLE
ERROR in Error: Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by AbhilashNagaraj** [swimlane/ngx-datatable#1284]
ERROR in Error: Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
at Object.pitch (D:\SarasManthan.Core\SarasManthan\SarasManthan.Core.App\node_modules\extract-text-webpack-plugin\dist\loader.js:53:11)
at Object. (D:/SarasManthan.Core/SarasManthan/SarasManthan.Core.App/node_modules//release/components/datatable.component.css:70:7)
at webpack_require (D:/SarasManthan.Core/SarasManthan/SarasManthan.Core.App/node_modules//release/components/datatable.component.css:20:30)
at D:/SarasManthan.Core/SarasManthan/SarasManthan.Core.App/node_modules//release/components/datatable.component.css:63:18
at D:/SarasManthan.Core/SarasManthan/SarasManthan.Core.App/node_modules//release/components/datatable.component.css:66:10
at ContextifyScript.Script.runInContext (vm.js:32:29)
at ContextifyScript.Script.runInNewContext (vm.js:38:15)
at Object.runInNewContext (vm.js:91:38)
at WebpackResourceLoader._evaluate (D:\SarasManthan.Core\SarasManthan\SarasManthan.Core.App\node_modules@ngtools\webpack\src\resource_loader.js:110:40)
at Compilation.compilation.plugin (D:\SarasManthan.Core\SarasManthan\SarasManthan.Core.App\node_modules@ngtools\webpack\src\resource_loader.js:58:26)
at Compilation.applyPluginsAsyncSeries (D:\SarasManthan.Core\SarasManthan\SarasManthan.Core.App\node_modules\tapable\lib\Tapable.js:206:13)
Child html-webpack-plugin for "Index.cshtml":
1 asset
[0] ./node_modules/html-webpack-plugin/lib/loader.js!./Views/Home/Index.cshtml 5.93 kB {0} [built]
factory:1616ms building:29ms = 1645ms
[2] (webpack)/buildin/global.js 509 bytes {0} [built]
[] -> factory:17ms building:3ms = 20ms
[3] (webpack)/buildin/module.js 517 bytes {0} [built]
[] -> factory:17ms building:3ms = 20ms
+ 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/nouislider/distribute/nouislider.css:
2 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/bootstrap/dist/css/bootstrap.css:
5 assets
8 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/font-awesome/css/font-awesome.css:
5 assets
9 modules
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build:prod" "--color=always"
npm ERR! node v7.9.0
npm ERR! npm v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! saras_manthan@1.0.0 build:prod: webpack --env=prod --progress --profile --colors
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the saras_manthan@1.0.0 build:prod script 'webpack --env=prod --progress --profile --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the saras_manthan package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! webpack --env=prod --progress --profile --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs saras_manthan
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls saras_manthan
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

How to fix for prod-build?

**Comment by Sqrrl** [comment]
Struggle a bit with this, too.

This worked for me:
```javascript
      {
        test: /\.css$/,
        exclude: /ngx-datatable/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader'
            }
          ]
        })
      },
      {
        test: /\.css$/,
        include: /ngx-datatable/,
        use: [
          {
            loader: 'to-string-loader'
          },
          {
            loader: 'css-loader'
          }
        ]
      }
```
