### ISSUE TITLE
Angular Universal 6 Error "Zone already loaded"

### ISSUE THREAD

**Issue by stephencawood** [swimlane/ngx-datatable#1529]
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
After building the SSR version of my Angular Universal 6.1.4 app, I get this runtime error trying to launch it:

> node dist/server.js
/dist/server.js:69253
        throw new Error('Zone already loaded.');
        ^

Error: Zone already loaded.
    at /dist/server.js:69253:15
    at /dist/server.js:69865:3
    at FUNCTION (/dist/server.js:69231:10)
    at Object.<anonymous> (/dist/server.js:69233:2)
    at __webpack_require__ (/dist/server.js:69108:30)
    at Object.<anonymous> (/dist/server.js:69168:1)
    at __webpack_require__ (/dist/server.js:69108:30)
    at Object.defineProperty.value (/dist/server.js:69157:18)
    at Object.<anonymous> (/dist/server.js:69160:10)
    at __webpack_require__ (/dist/server.js:20:30)

**Expected behavior**
The server-side app should run.

**Reproduction of the problem**
If I comment out the <ngx-datatable> tag from my component template, the error goes away and the app runs.

**What is the motivation / use case for changing the behavior?**
Can't run the app.

**Please tell us about your environment:**
MacOS High Sierra

"dependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/animations": "^6.1.4",
    "@angular/cdk": "^6.4.6",
    "@angular/cli": "~6.0.8",
    "@angular/common": "^6.1.4",
    "@angular/compiler": "^6.1.4",
    "@angular/compiler-cli": "^6.1.4",
    "@angular/core": "^6.1.4",
    "@angular/flex-layout": "^6.0.0-beta.16",
    "@angular/forms": "^6.1.4",
    "@angular/http": "^6.1.4",
    "@angular/material": "^6.4.6",
    "@angular/platform-browser": "^6.1.4",
    "@angular/platform-browser-dynamic": "^6.1.4",
    "@angular/platform-server": "^6.1.4",
    "@angular/router": "^6.1.4",
    "@fortawesome/angular-fontawesome": "^0.1.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.2",
    "@nguniversal/express-engine": "^6.1.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.1.0",
    "@ngx-share/button": "6.0.1",
    "@ngx-share/buttons": "6.0.1",
    "@ngx-share/core": "6.0.1",
    "@swimlane/ngx-datatable": "13.1.0",
    "@types/serve-favicon": "^2.2.30",
    "angular-font-awesome": "^3.1.2",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "rxjs": "^6.2.1",
    "serve-favicon": "^2.5.0",
    "ts-loader": "^4.5.0",
    "zone.js": "^0.8.26"
},
  "devDependencies": {
    "@angular/language-service": "^6.1.4",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "cypress": "^3.1.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "2.7.2",
    "webpack-cli": "^3.0.8"
  }

* **Table version:** 
ngx-datatable": "13.1.0"

I've tried with 13.0.0 and 12.0.0 and they also have issues with Angular Universal.

* **Angular version:** 
6.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
N/A

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.7.2

**Comment by JSMike** [comment]
I'm also getting this error with `@angular/core@7.04` and `@swimlane/ngx-datatable@14.0.0`
