### ISSUE TITLE
server side rendering with new angular cli fails

### ISSUE THREAD

**Issue by ehsanagh** [swimlane/ngx-datatable#1737]
Hi Everyone,
**I'm submitting an issue for server side rendering with new angular cli**
based on this link "https://github.com/swimlane/ngx-datatable/blob/master/docs/universal/server-side-rendering.md" we should introduce two injectable service ( ServerDimensionsHelper, ServerScrollBarHelper ) for SSR support. but there is  problem with "ServerDimensionsHelper"
```
[x ] bug report => search github for a similar issue or PR before submitting
[] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

when we run `npm run ng build` we get below error.
```
ate: 2019-09-02T07:44:12.427Z - Hash: ef8354dd966e154629bf - Time: 31826ms

WARNING in ./node_modules/express/lib/view.js 81:13-25
Critical dependency: the request of a dependency is an expression

ERROR in ./node_modules/cookie-signature/index.js
Module not found: Error: Can't resolve 'crypto' in '/Users/ehsan/Sites/lingemy-ui/node_modules/cookie-signature'
ERROR in ./node_modules/etag/index.js
Module not found: Error: Can't resolve 'crypto' in '/Users/ehsan/Sites/lingemy-ui/node_modules/etag'
ERROR in ./node_modules/destroy/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/ehsan/Sites/lingemy-ui/node_modules/destroy'
ERROR in ./node_modules/etag/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/ehsan/Sites/lingemy-ui/node_modules/etag'
ERROR in ./node_modules/express/lib/view.js
Module not found: Error: Can't resolve 'fs' in '/Users/ehsan/Sites/lingemy-ui/node_modules/express/lib'
ERROR in ./node_modules/mime/mime.js
Module not found: Error: Can't resolve 'fs' in '/Users/ehsan/Sites/lingemy-ui/node_modules/mime'
ERROR in ./node_modules/send/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/ehsan/Sites/lingemy-ui/node_modules/send'
ERROR in ./node_modules/express/lib/application.js
Module not found: Error: Can't resolve 'http' in '/Users/ehsan/Sites/lingemy-ui/node_modules/express/lib'
ERROR in ./node_modules/express/lib/response.js
Module not found: Error: Can't resolve 'http' in '/Users/ehsan/Sites/lingemy-ui/node_modules/express/lib'
ERROR in ./node_modules/express/lib/request.js
Module not found: Error: Can't resolve 'http' in '/Users/ehsan/Sites/lingemy-ui/node_modules/express/lib'
ERROR in ./node_modules/express/lib/request.js
Module not found: Error: Can't resolve 'net' in '/Users/ehsan/Sites/lingemy-ui/node_modules/express/lib'
ERROR in ./node_modules/content-disposition/index.js
Module not found: Error: Can't resolve 'path' in '/Users/ehsan/Sites/lingemy-ui/node_modules/content-disposition'
ERROR in ./node_modules/express/lib/application.js
Module not found: Error: Can't resolve 'path' in '/Users/ehsan/Sites/lingemy-ui/node_modules/express/lib'
ERROR in ./node_modules/express/lib/view.js
Module not found: Error: Can't resolve 'path' in '/Users/ehsan/Sites/lingemy-ui/node_modules/express/lib'
ERROR in ./node_modules/express/lib/response.js
Module not found: Error: Can't resolve 'path' in '/Users/ehsan/Sites/lingemy-ui/node_modules/express/lib'
ERROR in ./node_modules/mime/mime.js
Module not found: Error: Can't resolve 'path' in '/Users/ehsan/Sites/lingemy-ui/node_modules/mime'
ERROR in ./node_modules/mime-types/index.js
Module not found: Error: Can't resolve 'path' in '/Users/ehsan/Sites/lingemy-ui/node_modules/mime-types'
ERROR in ./node_modules/send/index.js
Module not found: Error: Can't resolve 'path' in '/Users/ehsan/Sites/lingemy-ui/node_modules/send'
ERROR in ./node_modules/serve-static/index.js
Module not found: Error: Can't resolve 'path' in '/Users/ehsan/Sites/lingemy-ui/node_modules/serve-static'
ERROR in ./node_modules/destroy/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/ehsan/Sites/lingemy-ui/node_modules/destroy'
ERROR in ./node_modules/send/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/ehsan/Sites/lingemy-ui/node_modules/send'
ERROR in ./node_modules/body-parser/lib/read.js
Module not found: Error: Can't resolve 'zlib' in '/Users/ehsan/Sites/lingemy-ui/node_modules/body-parser/lib'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lingemy-ui@0.0.1 ng: `ng "build"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lingemy-ui@0.0.1 ng script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ehsan/.npm/_logs/2019-09-02T07_44_13_438Z-debug.log
```

**Expected behavior**

Build has to be success, but it fails.
**Reproduction of the problem**

since it's big and time taking, take clone of `angular universal starter` project, add `ngx-datatable` to it, update your angular CLI to latest one, and follow shared link above, try `ng build` 100% you get failure.

**What is the motivation / use case for changing the behavior?**

As per angular Developers, in the new CLI it checks that we should not import any server side modules like express or other node modules which are not supported in browser level into the application.

** In ServerDimensionsHelper we are importing `import { Request } from 'express';`  which is wrong, we should not use express in browser level source.**
Here is the source

```
import { Injectable, Inject } from '@angular/core';
import { Request } from 'express';
import { REQUEST } from '@nguniversal/express-engine/tokens';
import { DimensionsHelper } from '@swimlane/ngx-datatable';

@Injectable()
export class ServerDimensionsHelper extends DimensionsHelper {

  constructor(@Inject(REQUEST) private request: Request) {
    super();
  }

  getDimensions(element: Element): ClientRect {
    const width = parseInt(this.request.cookies['CH-DW'], 10) || 1000;
    const height = parseInt(this.request.cookies['CH-DH'], 10) || 800;

    const adjustedWidth = width;
    const adjustedHeight = height;


    return {
      height: adjustedHeight,
      bottom: 0,
      top: 0,
      width: adjustedWidth,
      left: 0,
      right: 0
    };
  }
}
```

**Please tell us about your environment:**

I'm using MAC OS Mojave and nod 10.16.3 , below is more data.
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/ehsan/.nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/Users/ehsan/.nvm/versions/node/v10.16.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ng',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'preng', 'ng', 'postng' ]
5 info lifecycle lingemy-ui@0.0.1~preng: lingemy-ui@0.0.1
6 info lifecycle lingemy-ui@0.0.1~ng: lingemy-ui@0.0.1
7 verbose lifecycle lingemy-ui@0.0.1~ng: unsafe-perm in lifecycle true
8 verbose lifecycle lingemy-ui@0.0.1~ng: PATH: /Users/ehsan/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ehsan/Sites/lingemy-ui/node_modules/.bin:/Users/ehsan/.rvm/gems/ruby-2.4.0/bin:/Users/ehsan/.rvm/gems/ruby-2.4.0@global/bin:/Users/ehsan/.rvm/rubies/ruby-2.4.0/bin:/Users/ehsan/.nvm/versions/node/v10.16.3/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/ehsan/.rvm/gems/ruby-2.4.0/bin:/Users/ehsan/.rvm/gems/ruby-2.4.0@global/bin:/Users/ehsan/.rvm/rubies/ruby-2.4.0/bin:/usr/local/sbin:/Users/ehsan/.rvm/bin
9 verbose lifecycle lingemy-ui@0.0.1~ng: CWD: /Users/ehsan/Sites/lingemy-ui
10 silly lifecycle lingemy-ui@0.0.1~ng: Args: [ '-c', 'ng "build"' ]
11 silly lifecycle lingemy-ui@0.0.1~ng: Returned: code: 1  signal: null
12 info lifecycle lingemy-ui@0.0.1~ng: Failed to exec ng script
13 verbose stack Error: lingemy-ui@0.0.1 ng: `ng "build"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/ehsan/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/ehsan/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid lingemy-ui@0.0.1
15 verbose cwd /Users/ehsan/Sites/lingemy-ui
16 verbose Darwin 18.7.0
17 verbose argv "/Users/ehsan/.nvm/versions/node/v10.16.3/bin/node" "/Users/ehsan/.nvm/versions/node/v10.16.3/bin/npm" "run" "ng" "build"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error lingemy-ui@0.0.1 ng: `ng "build"`
22 error Exit status 1
23 error Failed at the lingemy-ui@0.0.1 ng script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

* **Table version:** 

Since ngx-databale doesn't support SSR and we should d tricky actions, YES, it's related t all version I think.

* **Angular version:** 

`8.2.4`

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

it's in build stage, not related to any browser.

**Comment by ehsanagh** [comment]
Current workaround  is that we can change the `ServerDimensionsHelper ` to below.

```
import { Injectable, Inject } from '@angular/core';
import { DimensionsHelper } from '@swimlane/ngx-datatable';

@Injectable()
export class ServerDimensionsHelper extends DimensionsHelper {

  constructor() {
    super();
  }

  getDimensions(element: Element): ClientRect {
    const width = 1000;
    const height = 800;

    const adjustedWidth = width;
    const adjustedHeight = height;


    return {
      height: adjustedHeight,
      bottom: 0,
      top: 0,
      width: adjustedWidth,
      left: 0,
      right: 0
    };
  }
}

```
