### ISSUE TITLE
when adding NgxDatatableModule to the import section I am getting error

### ISSUE THREAD

**Issue by LirazRom** [swimlane/ngx-datatable#600]
when adding the module to the imports, i am getting
Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
        </span>
      </span>
      [ERROR ->]<ng-template
        *ngIf="column.headerTemplate"
        [ngTemplateOutlet]="column.headerTemplate""): DataTableHeaderCellComponent@20:6 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angula…, _nativeError: ZoneAwareError, __zone_symbol__currentTask: ZoneTask, __zone_symbol__stack: "Error: Template parse errors:↵'ng-template' is not…http://localhost:4200/vendor.bundle.js:137009:35)", __zone_symbol__message: "Template parse errors:↵'ng-template' is not a know…derTemplate""): DataTableHeaderCellComponent@20:6"} Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
        </span>
      </span>
      [ERROR ->]<ng-template
        *ngIf="column.headerTemplate"
        [ngTemplateOutlet]="column.headerTemplate""): DataTableHeaderCellComponent@20:6
    at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:137455:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:86842:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:7237:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:20794:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:58091:68)
    at http://localhost:4200/vendor.bundle.js:57974:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:57974:19)
    at createResult (http://localhost:4200/vendor.bundle.js:57856:19)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:136797:26)
    at Zone.run (http://localhost:4200/vendor.bundle.js:136589:43)
    at http://localhost:4200/vendor.bundle.js:137176:57
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:136830:31)
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:136629:47)
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:137009:35)

**Comment by IbrahimElkhatib** [comment]
It seems that you are using version 7.0.0 with Angular2
check the change log: 
BREAKING: Update to Angular4!
If you need support for ~Angular2, use version 6.x.

**Comment by amcdnl** [comment]
Yes, @IbrahimElkhatib is correct. 7.x is for Angular4.
