### ISSUE TITLE
Cannot include ngx-datatable module into the project

### ISSUE THREAD

**Issue by Crizstian** [swimlane/ngx-datatable#615]
Im following the instructions and am i not able to use the module.

**I'm submitting a ...**
```
[ X ] bug report 
```

**Please tell us about your environment:** Angular-CLI 1.0

* **Table version:** 0.7

* **Angular version:** 2.4.0

* **Browser:** [all]

```
Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element:

If 'ng-template' is an Angular component, then verify that it is part of this module.
If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("


[ERROR ->]<ng-template
*ngIf="column.headerTemplate"
[ngTemplateOutlet]="column.headerTemplate""): DataTableHeaderCellComponent@20:6 ; Zone: ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
'ng-template' is not a known element:
If 'ng-template' is an Angula……} Error: Template parse errors:
'ng-template' is not a known element:
If 'ng-template' is an Angular component, then verify that it is part of this module.
If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("


[ERROR ->]<ng-template
*ngIf="column.headerTemplate"
[ngTemplateOutlet]="column.headerTemplate""): DataTableHeaderCellComponent@20:6
at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:997:33)
at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:75607:16)
at new SyntaxError (http://localhost:4200/vendor.bundle.js:6786:16)
at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:20920:19)
at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:55316:68)
at http://localhost:4200/vendor.bundle.js:55199:62
at Set.forEach (native)
at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:55199:19)
at createResult (http://localhost:4200/vendor.bundle.js:55081:19)
at ZoneDelegate.webpackJsonp.1005.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:339:26)
at Zone.webpackJsonp.1005.Zone.run (http://localhost:4200/polyfills.bundle.js:131:43)
at http://localhost:4200/polyfills.bundle.js:718:57
at ZoneDelegate.webpackJsonp.1005.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:372:31)
at Zone.webpackJsonp.1005.Zone.runTask (http://localhost:4200/polyfills.bundle.js:171:47)
at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:551:35)
consoleError @ zone.js:522
handleUnhandledRejection @ zone.js:527
_loop_1 @ zone.js:562
drainMicroTaskQueue @ zone.js:566
Promise.resolve (async)
scheduleQueueDrain @ zone.js:505
scheduleMicroTask @ zone.js:513
webpackJsonp.1005.ZoneDelegate.scheduleTask @ zone.js:356
webpackJsonp.1005.Zone.scheduleTask @ zone.js:196
webpackJsonp.1005.Zone.scheduleMicroTask @ zone.js:207
scheduleResolveOrReject @ zone.js:711
webpackJsonp.1005.ZoneAwarePromise.then @ zone.js:800
webpackJsonp.1005.ZoneAwarePromise.all @ zone.js:780
JitCompiler._loadModules @ compiler.js:173
JitCompiler.compileModuleAndComponents @ compiler.js:125
JitCompiler.compileModuleAsync @ compiler.js:91
PlatformRef.bootstrapModuleWithZone @ application_ref.js:390
PlatformRef.bootstrapModule @ application_ref.js:365
417 @ main.ts:11
webpack_require @ bootstrap c5c943b…:52
1009 @ main.bundle.js:7
webpack_require @ bootstrap c5c943b…:52
webpackJsonpCallback @ bootstrap c5c943b…:23
(anonymous) @ main.bundle.js:1
zone.js:524 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Error: Template parse errors:
'ng-template' is not a known element:
1.……}
```

**Comment by Dedac** [comment]
The datatable only supports Angular 4 with version 7.0.0, you need to target version 6.3.0 to use it with angular 2.4

**Comment by Crizstian** [comment]
thanks with the 6.3.0 version works
