### ISSUE TITLE
TypeError on page load

### ISSUE THREAD

**Issue by Deilan** [swimlane/ngx-datatable#707]
**I'm submitting a ...**  (check one with "x")
bug report

**Current behavior**
Error on page load:
```
Unhandled exception has occurred: TypeError
TypeError: Cannot read property 'apply' of undefined
    at XMLHttpRequest.desc.get [as ontimeout] (c:\Ekopoint\ngx-datatable\~\zone.js\dist\zone.js:1265:1)
    at XHRLocalObject../node_modules/sockjs-client/lib/transport/browser/abstract-xhr.js.AbstractXHRObject._cleanup (c:\Ekopoint\ngx-datatable\~\sockjs-client\lib\transport\browser\abstract-xhr.js:149:1)
    at XMLHttpRequest.xhr.onreadystatechange (c:\Ekopoint\ngx-datatable\~\sockjs-client\lib\transport\browser\abstract-xhr.js:125:1)
    at XMLHttpRequest.wrapFn (c:\Ekopoint\ngx-datatable\~\zone.js\dist\zone.js:1230:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (c:\Ekopoint\ngx-datatable\~\zone.js\dist\zone.js:398:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.runTask (c:\Ekopoint\ngx-datatable\~\zone.js\dist\zone.js:165:1)
    at XMLHttpRequest.ZoneTask.invoke (c:\Ekopoint\ngx-datatable\~\zone.js\dist\zone.js:460:1)
```

**Expected behavior**
No error.

**Reproduction of the problem**

0. Clone the repository
1. `npm start`
2. Open `http://localhost:9999/` in Chrome 

**Please tell us about your environment:**
Windows 8.1 x64
Node 7.7.3

* **Table version:** 0.8.x
The latest from the repo

* **Angular version:** 2.0.x
The latest from the repo

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 58.0.3029.81

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
The latest from the repo

**Comment by olaf89** [comment]
Its zone.js version 8.8 issue not datatable

**Comment by amcdnl** [comment]
Ya, I'm getting this too :S .... I recommend downgrading zone.
