### ISSUE TITLE
Cannot build with uglifyjs, changing to uglify-js works

### ISSUE THREAD

**Issue by arlowhite** [swimlane/ngx-datatable#784]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

`npm run package` fails with uglifyjs
There is a deprecation warning saying uglifyjs migrated to uglify-js

**Expected behavior**

`npm run package` should work.

**Reproduction of the problem**

`git checkout 9.2.0`
`rm -rf node_modules`
`npm install`
`npm run package`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Node v6.9.1
npm 4.6.1

* **Table version:** 9.2.0

* **Angular version:** N/A

* **Browser:** N/A
* **Language:** all

* **Solution**
I changed to
`"uglify-js": "^2.8.27"`
`npm run package` works for me now.

**Comment by arlowhite** [comment]
If you merge #786 I include this change because I was not able to build without it.

**Comment by arlowhite** [comment]
Just did another fresh build. By default uglifyjs@2.4.11 is installed.

npm run package error:
```
> @swimlane/ngx-datatable@9.3.0 package:minify /home/whitea/Code/forks/ngx-datatable
> uglifyjs release/index.js --source-map release/index.min.js.map --source-map-url release/index.js.map --compress --mangle --screw-ie8 --output release/index.min.js

Supported options:
  content         null
  filename        null
  includeSources  false
  root            null
  url             null
ERROR: `release/index.min.js.map` is not a supported option
    at DefaultsError.get (eval at <anonymous> (/home/whitea/Code/forks/ngx-datatable/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:79:23)
    at fatal (/home/whitea/Code/forks/ngx-datatable/node_modules/uglify-js/bin/uglifyjs:279:52)
    at run (/home/whitea/Code/forks/ngx-datatable/node_modules/uglify-js/bin/uglifyjs:234:9)
    at Object.<anonymous> (/home/whitea/Code/forks/ngx-datatable/node_modules/uglify-js/bin/uglifyjs:164:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @swimlane/ngx-datatable@9.3.0 package:minify: `uglifyjs release/index.js --source-map release/index.min.js.map --source-map-url release/index.js.map --compress --mangle --screw-ie8 --output release/index.min.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @swimlane/ngx-datatable@9.3.0 package:minify script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/whitea/.npm/_logs/2017-06-14T19_36_03_964Z-debug.log
ERROR: "package:minify" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @swimlane/ngx-datatable@9.3.0 package: `npm-run-all -s clean copy:build build:sass package:replace-scss package:aot build:package package:minify copy:styles clean:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @swimlane/ngx-datatable@9.3.0 package script.
```

**Comment by arlowhite** [comment]
I'll look at creating a PR just for uglify-js update. If I can't get the latest version working, I'll just use 2.8
